Config({
    "network-name": "ميكروتكنيك",
    "service-number": "777777777",
    "login-type": "user", 
    "speed-select": 0 ,
    "speed-var":"domain",
    "speed-option":`<option value="" selected disabled hidden>أختيار سرعة الإنترنت</option><option value="" >سرعة أفتراضية </option><option value="128K/512K">سرعة منخفضة 512 </option><option value="256K/1024K">سرعة عادية 1 ميجا</option><option value="512K/2048K">سرعة متوسطة 2 ميجا</option><option value="1024K/4096K">سرعة عالية جدا 4 ميجا</option>`,
    "news-line": `مرحبا  بكم  في شبكتنا * تذكر ان الله ينظر إليك فلا تجعله أهون الناظرين إليك
        ` ,
    "input-autocomplete": "on",
    "input-type": "text",
    "input-rm-white-spaces": 1,
    "input-to-lower": 0,
    "input-to-upper": 0,
    "input-to-arabic-numbers": 1,
    "input-only-numbers": 0,
    "input-no-numbers": 0,
    "input-only-alphanumeric": 0,
    "enable-hot-cookie": 1 ,
    "enable-hot-blocker": 1,
    "clear-router-cookie": 1,
    "clear-hot-cookie": 1,
    "block-time": 2,
    "try-count": 5,
    "warn-when": 3,
    "warn-message": "تحذير !! عدد محاولاتك الخاطئة اصبح {{tryCounter}} محاولات, عدد المحاولات المسموح بها هي {{tryCount}} محاولات فقط, عدد محاولاتك المتبقية {{restTryCount}} محاولات, سيتم حظرك لمدة {{blockTime}} دقائق اذا تجاوزت العدد المسموح للمحاولات",
    "price-button": true,
    "sell-point-button": true,
    "show-date-field": true,
    "loan-button": false,
    "loan-text": `يوجد لدينا خدمة توفير ....`,
    "redirect-to-esterahah": "",
    "redirect-to-mobasher": "",
    "profiles": [{"price":"100  ريال","time":"3 ساعات","transfer":"250 ميجا","validity":"3 أيام"}] ,
    "sell-points": [{"name":"نقطة بيع"},{"name":"نقطة بيع"},{"name":"نقطة بيع"},{"name":"نقطة بيع"},{"name":"نقطة بيع"},{"name":"نقطة بيع"}]
})
