Config({
    "network-name": "يمن نت ",
    "service-number": "776937881",
    "login-type": "both", 
    "speed-select": 1 ,
    "speed-var":"speed",
    "speed-option":`<option value="" selected disabled hidden>أختيار سرعة الإنترنت</option><option value="" >سرعة أفتراضية </option><option value="128K/512K">سرعة منخفضة </option><option value="256K/1024K">سرعة عادية  </option><option value="512K/2048K">سرعة متوسطة </option><option value="1024K/4096K">سرعة عالية جدا </option>`,
    "news-line": `مرحبا  بكم  في شبكتنا * تذكر ان الله ينظر إليك فلا تجعله أهون الناظرين إليك * حياكم عندنا و ارحبوا   
        ` ,
    "input-autocomplete": "on",
    "input-type": "text",
    "input-rm-white-spaces": 1,
    "input-to-lower": 0,
    "input-to-upper": 0,
    "input-to-arabic-numbers": 1,
    "input-only-numbers": 0,
    "input-no-numbers": 0,
    "input-only-alphanumeric": 0,
    "enable-hot-cookie": 1 ,
    "enable-hot-blocker": 1,
    "clear-router-cookie": 1,
    "clear-hot-cookie": 1,
    "block-time": 5,
    "try-count": 5,
    "warn-when": 3,
    "warn-message": "تحذير !! عدد محاولاتك الخاطئة اصبح {{tryCounter}} محاولات, عدد المحاولات المسموح بها هي {{tryCount}} محاولات فقط, عدد محاولاتك المتبقية {{restTryCount}} محاولات, سيتم حظرك لمدة {{blockTime}} دقائق اذا تجاوزت العدد المسموح للمحاولات",
    "price-button": true,
    "sell-point-button": true,
    "show-date-field": true,
    "loan-button": true,
    "loan-text": `يوجد لدينا خدمة توفير .... جميع انواع الكروت الصغيرة و الكبيرة و كل الاحجام عريظة النطاق و ارحبوا`,
    "redirect-to-esterahah": "http://google.com",
    "redirect-to-mobasher": "ymen.net",
    "profiles": [{"price":"100  ريال","time":"3 ساعات","transfer":"250 ميجا","validity":"3 أيام"},{"price":"400 ريال","time":"5 ساعات","transfer":"400 جيجا","validity":"760 يوم"},{"price":"500 سنة","time":"300 رسيال","transfer":"5 ساعات","validity":"10 ايام"},{"price":"200 سنة","time":"300 رسيال","transfer":"5 ساعات","validity":"10 ايام"},{"price":"200 سنة","time":"300 رسيال","transfer":"5 ساعات","validity":"10 ايام"}] ,
    "sell-points": [{"name":"نقطة بيع"},{"name":"نقطة بيع"},{"name":"نقطة بيع"},{"name":"نقطة بيع"},{"name":"نقطة بيع"},{"name":"نقطة بيع"},{"name":"اليمن السعيد"},{"name":"اليمن السعيد"},{"name":"اليمن السعيد"}]
})
